pipeline:

  build-project:
    image: quay.io/ukhomeofficedigital/openjdk8
    commands:
      - export SPRING_PROFILES_ACTIVE='development, local, postgres'
      - export SERVER_PORT='8080'
      - export DOCS_QUEUE_NAME='document-queue'
      - export DOCS_QUEUE_DLQ_NAME='document-queue-dlq'
      - export CASE_QUEUE_NAME='case-queue'
      - export DOCS_TRUSTEDS3BUCKETNAME='trusted-bucket'
      - export DOCS_UNTRUSTEDS3BUCKETNAME='untrusted-bucket'
      - export HOCSCONVERTER_ROOT='http4://converter:8080'
      - export CLAMAV_ROOT='http4://clamav:8080'
      - export DB_HOST='postgres'
      - export AWS_LOCAL_HOST='localstack'
      - ./gradlew build
    when:
      event: [push, pull_request, tag]

  docker-build:
    image: docker:17.09.1
    environment:
    - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
    - docker build -t hocs-docs .
    when:
      branch: [master, refs/tags/*]
      event: [push, tag]

  install-docker-image:
    image: docker:17.09.1
    environment:
    - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
    - docker_password
    commands:
    - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
    - docker tag hocs-docs quay.io/ukhomeofficedigital/hocs-docs:build-$${DRONE_BUILD_NUMBER}
    - docker tag hocs-docs quay.io/ukhomeofficedigital/hocs-docs:latest
    - docker push quay.io/ukhomeofficedigital/hocs-docs:build-$${DRONE_BUILD_NUMBER}
    - docker push quay.io/ukhomeofficedigital/hocs-docs:latest  
    when:
      branch: master
      event: push

  tag-docker-image-with-git-tag:
    image: docker:17.09.1
    environment:
    - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
    - docker_password
    commands:
    - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
    - docker tag hocs-docs quay.io/ukhomeofficedigital/hocs-docs:$${DRONE_TAG}
    - docker push quay.io/ukhomeofficedigital/hocs-docs:$${DRONE_TAG}
    when:
      event: tag

  clone-kube-project:
    image: plugins/git
    commands:
    - git clone https://github.com/UKHomeOffice/kube-hocs-docs.git
    when:
      event: [push, tag, deployment]

  deploy-to-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
    - KUBE_NAMESPACE=cs-dev
    - ENVIRONMENT=dev
    - VERSION=build-${DRONE_BUILD_NUMBER}
    - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
    - hocs_docs_dev
    commands:
    - cd kube-hocs-docs
    - ./deploy.sh
    when:
      branch: master
      event: [push, tag]

  deployment:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
    - KUBE_NAMESPACE=cs-${DRONE_DEPLOY_TO}
    - ENVIRONMENT=${DRONE_DEPLOY_TO}
    - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
    - hocs_docs_dev
    - hocs_docs_qa
    commands:
    - cd kube-hocs-docs
    - ./deploy.sh
    when:
      event: deployment
      environment: [dev, qa]

  deploy-to-prod:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
    - KUBE_NAMESPACE=cs-prod
    - ENVIRONMENT=prod
    - VERSION=${IMAGE_VERSION}
    - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
    secrets:
    - hocs_docs_prod
    commands:
    - cd kube-hocs-docs
    - ./deploy.sh
    when:
      event: deployment
      environment: prod

services:
  postgres:
    image: quay.io/ukhomeofficedigital/postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
  localstack:
    image: localstack/localstack:latest
    environment:
      HOSTNAME_EXTERNAL: localstack
      DEFAULT_REGION: eu-west-2
      SERVICES: sqs,s3
  aws_cli:
    image: garland/aws-cli-docker
    command:
      - /bin/sh
      - -c
      - |
          aws --endpoint-url=http://localstack:4572 s3 mb s3://untrusted-bucket
          aws --endpoint-url=http://localstack:4572 s3 mb s3://trusted-bucket
          aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name case-queue
          aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name case-queue-dlq
          aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name document-queue
          aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name document-queue-dlq
          aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name reporting-queue
          aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name reporting-queue-dlq
    environment:
      AWS_ACCESS_KEY_ID: UNSET
      AWS_SECRET_ACCESS_KEY: UNSET
      AWS_DEFAULT_REGION: 'eu-west-2'
  converter:
    image: quay.io/ukhomeofficedigital/hocs-docs-converter
  clamav:
    image: lokori/clamav-rest
    environment:
      CLAMD_HOST: clamd
  clamd:
    image: quay.io/ukhomeofficedigital/clamav:v1.4.0