version: '3.1'

services:

  postgres:
    image: quay.io/ukhomeofficedigital/postgres-alpine
    restart: always
    ports:
      - "5432:5432"
    networks:
      - hocs-docs
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev

  clamd:
    image: mkodockx/docker-clamav:alpine
    ports:
      - "3310:3310/tcp"
    networks:
      - hocs-docs

  clamav:
    image: lokori/clamav-rest
    environment:
      - CLAMD_HOST=clamd
    ports:
      - "8086:8080"
    networks:
      - hocs-docs
    depends_on:
      - clamd

  localstack:
    image: localstack/localstack:0.11.2
    networks:
      - hocs-docs
    container_name: localstack-sqs-tool
    ports:
      - "4567-4597:4567-4597"
      - "8999:8080"
    environment:
      - SERVICES=sqs,sns,s3
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_EXECUTION_ENV=True
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - $PWD/src/test/resources/localstack:/docker-entrypoint-initaws.d

  converter:
    image: quay.io/ukhomeofficedigital/hocs-docs-converter:latest
    networks:
      - hocs-docs
    ports:
      - "8084:8080"
      - "7084:8000"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
      SERVER_PORT: 8080

networks:
  hocs-docs: