version: '3.1'

services:

  clamd:
    image: quay.io/ukhomeofficedigital/clamav:v1.4.0
    ports:
      - "3310:3310/tcp"

  clamav-rest:
     image: lokori/clamav-rest
     environment:
       - CLAMD_HOST=clamd
     ports:
       - "8086:8080"

  awsCli:
    image: garland/aws-cli-docker
    command:
          - /bin/sh
          - -c
          - |
              sleep 2
              aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name cs-dev-case-sqs
              aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name cs-dev-document-sqs
              aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name cs-dev-document-sqs-dlq
              aws --endpoint-url=http://localstack:4572 s3 mb s3://cs-dev-untrusted-s3
              aws --endpoint-url=http://localstack:4572 s3 mb s3://cs-dev-trusted-s3
    environment:
      AWS_ACCESS_KEY_ID: UNSET
      AWS_SECRET_ACCESS_KEY: UNSET
      AWS_DEFAULT_REGION: eu-west-2
    depends_on:
     - localstack

  localstack:
    image: localstack/localstack:latest
    ports:
      - 8088:8080
      - 4567-4583:4567-4583
    environment:
      DEFAULT_REGION: eu-west-2
      SERVICES: sqs,s3

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      SERVICES: sqs,s3