version: '3.8'

services:

  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    networks:
      - hocs-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  clamd:
    image: mkodockx/docker-clamav:buster-slim
    ports:
      - "3310:3310/tcp"
    networks:
      - hocs-network

  clamav:
    image: lokori/clamav-rest
    environment:
      - CLAMD_HOST=clamd
    ports:
      - "8086:8080"
    networks:
      - hocs-network
    depends_on:
      - clamd

  localstack:
    image: localstack/localstack:0.11.1
    ports:
      - "9000:8080"
      - "4572:4572"
      - "4576:4576"
      - "4575:4575"
      - "4571:4571"
      - "4578:4578"
    networks:
      - hocs-network
    environment:
      HOSTNAME_EXTERNAL: localstack
      DEFAULT_REGION: eu-west-2
      SERVICES: sqs,s3,sns

  aws_cli:
    image: xueshanf/awscli
    command:
      - /bin/sh
      - -c
      - |
        sleep 30
        aws --version
        aws --endpoint-url=http://localstack:4572 s3 mb s3://untrusted-bucket
        aws --endpoint-url=http://localstack:4572 s3 mb s3://trusted-bucket
        aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name document-queue
        aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name document-queue-dlq
        aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name audit-queue
        aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name audit-queue-dlq
        aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name search-queue
        aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name search-queue-dlq
        aws --endpoint-url=http://localstack:4575 sns create-topic --name hocs-audit-topic
        aws --endpoint-url=http://localstack:4575 sns subscribe --topic-arn arn:aws:sns:eu-west-2:123456789012:hocs-audit-topic --attributes RawMessageDelivery=true --protocol sqs --notification-endpoint arn:aws:sns:eu-west-2:123456789012:audit-queue
        aws --endpoint-url=http://localstack:4575 sns subscribe --topic-arn arn:aws:sns:eu-west-2:123456789012:hocs-audit-topic --attributes RawMessageDelivery=true --protocol sqs --notification-endpoint arn:aws:sns:eu-west-2:123456789012:search-queue
        aws --endpoint-url=http://localstack:4575 sns set-subscription-attributes --subscription-arn $$(aws --endpoint-url=http://localstack:4575 sns list-subscriptions-by-topic --topic-arn arn:aws:sns:eu-west-2:123456789012:hocs-audit-topic --output json | jq --raw-output '.Subscriptions[0].SubscriptionArn') --attribute-name RawMessageDelivery --attribute-value true
        aws --endpoint-url=http://localstack:4575 sns set-subscription-attributes --subscription-arn $$(aws --endpoint-url=http://localstack:4575 sns list-subscriptions-by-topic --topic-arn arn:aws:sns:eu-west-2:123456789012:hocs-audit-topic --output json | jq --raw-output '.Subscriptions[1].SubscriptionArn') --attribute-name RawMessageDelivery --attribute-value true
        aws --endpoint-url=http://localstack:4575 sns list-subscriptions
    environment:
      AWS_ACCESS_KEY_ID: UNSET
      AWS_SECRET_ACCESS_KEY: UNSET
      AWS_DEFAULT_REGION: 'eu-west-2'
    networks:
      - hocs-network
    depends_on:
      - localstack

networks:
  hocs-network:
